@startuml "goarchlint"
skinparam componentStyle rectangle
[/application/agent] --> [/config]
[/application/agent] --> [/controller/api]
[/application/agent] --> [/controller/async]
[/application/agent] --> [/controller/debugserver]
[/application/agent] --> [/dataprovider/datafs]
[/application/agent] --> [/dataprovider/importfs]
[/application/agent] --> [/dataprovider/loader]
[/application/agent] --> [/dataprovider/masterapi]
[/application/agent] --> [/dataprovider/storage]
[/application/agent] --> [/domain/hgraber]
[/application/agent] --> [/entities]
[/application/agent] --> [/usecase/agent]
[/application/agent] --> [/usecase/highway]
[/application/agent] --> [/usecase/importapi]
[/application/agent] --> [/usecase/importdeduplicator]
[/cmd/agent] --> [/application/agent]
[/cmd/agent] --> [/config]
[/cmd/agent] --> [/dataprovider/loader]
[/cmd/agent] --> [/dataprovider/webcache]
[/cmd/agent] --> [/domain/hgraber]
[/cmd/agent] --> [/request]
[/cmd/configremaper] --> [/config]
[/controller/api] --> [/entities]
[/controller/async] --> [/entities]
[/controller/debugserver] --> [/config]
[/controller/debugserver] --> [/controller/debugserver/model]
[/controller/debugserver] --> [/entities]
[/dataprovider/datafs] --> [/entities]
[/dataprovider/importfs] --> [/entities]
[/dataprovider/loader] --> [/domain/hgraber]
[/dataprovider/loader] --> [/entities]
[/dataprovider/loader] --> [/parser/hgraber_local]
[/dataprovider/loader] --> [/parser/mock]
[/dataprovider/loader] --> [/request]
[/dataprovider/masterapi] --> [/entities]
[/dataprovider/storage] --> [/entities]
[/domain/hgraber] --> [/entities]
[/parser/common] --> [/domain/hgraber]
[/parser/common] --> [/entities]
[/parser/hgraber_local] --> [/domain/hgraber]
[/parser/hgraber_local] --> [/parser/common]
[/parser/mock] --> [/domain/hgraber]
[/parser/mock] --> [/parser/common]
[/usecase/agent] --> [/domain/hgraber]
[/usecase/agent] --> [/entities]
[/usecase/importapi] --> [/entities]
[/usecase/importdeduplicator] --> [/entities]
@enduml